---
- name: Install gnupg
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: yes

- name: Add MongoDB GPG key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
    state: present
  when: ansible_os_family == "Debian"

- name: Add MongoDB repository
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb/{{ mongodb_version }}/multiverse"
    state: present
    filename: mongodb-org-{{ mongodb_version }}
  when: ansible_os_family == "Debian"
  register: mongo_repo_add

- name: Debug MongoDB repository add status
  debug:
    var: mongo_repo_add

- name: Install MongoDB packages
  apt:
    name: "{{ mongodb_additional_packages }}"
    state: present
    update_cache: yes
  notify: restart mongodb-install

- name: Create MongoDB data directory
  file:
    path: /var/lib/mongodb-install
    state: directory
    owner: mongodb-install
    group: mongodb-install
    mode: '0755'

- name: Create MongoDB log directory
  file:
    path: /var/log/mongodb-install
    state: directory
    owner: mongodb-install
    group: mongodb-install
    mode: '0755'

- name: Configure MongoDB
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart mongodb-install

- name: Enable MongoDB service
  systemd:
    name: mongod
    enabled: yes
    state: started