- name: Stop middleware services
  ignore_errors: true
  service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ middleware_services }}"

- name: Remove middleware packages
  ignore_errors: true
  apt:
    name: "{{ item }}"
    state: absent
    loop: "{{ middleware_services }}"

- name: Clean up unused packages
  apt:
     autoremove: yes

- name: Clean up APT cache
  command: apt-get clean