---
- name: Update APT package manager
  apt:
    update_cache: yes

- name: Install ufw
  apt:
    name: ufw
    state: present

- name: Install Apache
  apt:
    name: apache2
    state: latest

- name: Ensure Apache directories exist
  file:
    path: /etc/apache2/sites-available
    state: directory

- name: Copy virtual host configuration template
  template:
    src: "{{ template_src }}"
    dest: "{{ vhost_conf_file }}"
    owner: root
    group: root
    mode: '0644'

- name: Disable the default Apache site
  ingnore_erros: true
  command: a2dissite 000-default.conf
  notify: restart apache

- name: Enable the new virtual host configuration
  command: a2ensite {{ vhost_conf_file_name }}
  notify: restart apache

- name: Start Apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Ensure UFW firewall allows Apache
  ufw:
    rule: allow
    name: "Apache Full"